language: node_js

node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"

before_script:
  - "npm run build"
  - "npm link"

script:
  - "pbr-up"
  - "pbr-up -h"
  - "pbr-up -v"
  - "pbr-up help"
  - "pbr-up config"
  - "pbr-up config get"
  - "pbr-up config list"
  - "pbr-up whoami"
  - "pbr-up logout"
  - "pbr-up upload"
  - "pbr-up help help"
  - "pbr-up help config"
  - "pbr-up help whoami"
  - "pbr-up help login"
  - "pbr-up help logout"
  - "pbr-up help upload"
  - "pbr-up update"

after_script:
  - "npm unlink"

before_deploy:
  - "npm run clean"
  - "npm run build -- -P ./tsconfig.prod.json"

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node_js: "node"